[env]
_.path = ["target/debug", "test/bats/bin"]

[tools]
age = "latest"
"cargo:cargo-msrv" = "latest"
cargo-binstall = "latest"
"cargo:cargo-edit" = "latest"
git-cliff = "latest"
hk = "latest"
pkl = "latest"
prettier = "latest"
shellcheck = "latest"
shfmt = "latest"
actionlint = "latest"
1password = "latest"
bitwarden = "latest"
vault = "latest"
usage = "latest"

[tasks.test]
description = "Run both cargo and bats tests"
depends = ["test:cargo", "test:bats"]

[tasks."test:cargo"]
description = "Run cargo tests only"
run = "cargo test"

[tasks."test:bats"]
description = "Run bats tests only"
depends = ["build"]
run = "fnox exec -- bats --jobs 4 --no-parallelize-within-files {{arg(name='test', var=true, default='test')}}"

[tasks."test:bats:fork"]
description = "Run bats tests simulating forked PR (no age key access)"
depends = ["build"]
env = { FNOX_AGE_KEY = "/tmp/nonexistent-age-key.txt" }
run = "fnox exec -- bats --jobs 4 --no-parallelize-within-files {{arg(name='test', var=true, default='test')}}"

[tasks.cargo-test]
description = "Run cargo tests only"
run = "cargo test"

[tasks.lint]
run = "hk check --all --slow"

[tasks.lint-fix]
run = "hk fix --all --slow"

[tasks.build]
description = "Build the project"
run = "cargo build"

[tasks.ci]
description = "Run full CI check (build, test, lint)"
depends = ["build", "test", "lint"]

[tasks.render]
description = "Render documentation from usage"
depends = ["render:*"]

[tasks."render:usage"]
description = "Generate CLI documentation from usage"
depends = ["build"]
run = [
  "fnox usage > fnox.usage.kdl",
  "rm -rf docs/cli && mkdir -p docs/cli",
  "usage g markdown -mf fnox.usage.kdl --out-dir docs/cli --url-prefix /cli",
  "usage g json -f fnox.usage.kdl > docs/cli/commands.json",
  "prettier --write docs/cli",
  "git add fnox.usage.kdl docs/cli",
]
